import type { HttpContext } from '@adonisjs/core/http'
import bcrypt from 'bcryptjs'
import type User from '#models/user'
import { securitySettings } from '#services/app_settings'
import {
  RECOVERY_CODE_COUNT,
  canSelfDisable,
  citizenIdOf,
  disableTwoFactor,
  isTwoFactorRequired,
  regenerateRecoveryCodes,
  remainingRecoveryCodes,
  twoFactorRecord,
} from '#services/two_factor'
import { writeAudit } from '#services/audit'

const maskCid = (cid: string | null) => (cid ? `${cid.slice(0, 1)}-xxxx-xxxxx-${cid.slice(10, 12)}-${cid.slice(12)}` : null)

/** /account/security — the signed-in user's own 2FA: status, new recovery codes, switch off. */
export default class AccountSecurityController {
  async show({ view, auth, session }: HttpContext) {
    const user = auth.user as User
    const [record, settings] = await Promise.all([twoFactorRecord(user.id), securitySettings()])

    return view.render('pages/account/security', {
      twofa: {
        enabled: !!record?.method,
        method: record?.method ?? null,
        enabledAt: record?.enabledAt ?? null,
        citizenIdMasked: record?.method === 'line' ? maskCid(citizenIdOf(record)) : null,
        remainingCodes: record?.method ? await remainingRecoveryCodes(user.id) : 0,
        totalCodes: RECOVERY_CODE_COUNT,
        required: await isTwoFactorRequired(user, record, settings),
        canDisable: record?.method ? await canSelfDisable(user, record) : false,
        systemEnabled: settings.twofaEnabled,
      },
      message: session.flashMessages.get('message'),
      messageType: session.flashMessages.get('messageType'),
    })
  }

  async regenerateCodes(ctx: HttpContext) {
    const { request, auth, session, response } = ctx
    const user = auth.user as User
    if (!(await this.passwordOk(user, request.input('current_password')))) {
      return this.flash(ctx, 'รหัสผ่านปัจจุบันไม่ถูกต้อง', 'error')
    }
    if (!(await twoFactorRecord(user.id))?.method) return this.flash(ctx, 'ยังไม่ได้เปิดใช้ 2FA', 'error')

    session.put('twofa.recoveryCodes', await regenerateRecoveryCodes(user.id))
    await writeAudit(ctx, {
      action: 'auth.2fa_codes_regenerated',
      entity: 'user',
      entityId: user.id,
      summary: `recovery codes regenerated by ${user.username}`,
    })
    return response.redirect('/2fa/recovery-codes')
  }

  async disable(ctx: HttpContext) {
    const { request, auth } = ctx
    const user = auth.user as User
    const record = await twoFactorRecord(user.id)
    if (!record?.method) return this.flash(ctx, 'ยังไม่ได้เปิดใช้ 2FA', 'error')
    if (!(await canSelfDisable(user, record))) {
      return this.flash(ctx, 'บัญชีนี้ถูกกำหนดให้ต้องใช้ 2FA ไม่สามารถปิดเองได้ — ติดต่อผู้ดูแลระบบ', 'error')
    }
    if (!(await this.passwordOk(user, request.input('current_password')))) {
      return this.flash(ctx, 'รหัสผ่านปัจจุบันไม่ถูกต้อง', 'error')
    }

    await disableTwoFactor(user.id)
    await writeAudit(ctx, {
      action: 'auth.2fa_disabled',
      entity: 'user',
      entityId: user.id,
      summary: `2FA disabled by ${user.username}`,
    })
    return this.flash(ctx, 'ปิดใช้งาน 2FA แล้ว', 'success')
  }

  private async passwordOk(user: User, password: unknown) {
    return typeof password === 'string' && password !== '' && bcrypt.compare(password, user.password)
  }

  private flash({ session, response }: HttpContext, message: string, type: 'success' | 'error') {
    session.flash('message', message)
    session.flash('messageType', type)
    return response.redirect('/account/security')
  }
}
